"""Extract structured fields from digital ordinary invoices.

The extractor uses text anchors and relative layout instead of one set of
absolute page coordinates:

    OCR JSON
    -> locate invoice sections and table headers
    -> locate values relative to those anchors
    -> validate the monetary relationship
    -> return fields consumed by matcher.py/risk_detector.py

It supports both the synthetic template generated by
generate_invoice_images.py and the common electronic ordinary-invoice layout
where buyer and seller blocks appear side by side. It does not call an LLM and
does not judge invoice risk.
"""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import asdict, dataclass
from datetime import date
from decimal import ROUND_HALF_UP, Decimal, InvalidOperation
from pathlib import Path
from typing import Any, Iterable

import pandas as pd


PROJECT_ROOT = Path(__file__).resolve().parent
DEFAULT_OUTPUT_DIR = PROJECT_ROOT / "data" / "generated" / "extracted_invoices"
DEFAULT_INVOICE_WORKBOOK = PROJECT_ROOT / "data" / "source" / "invoices.xlsx"


class InvoiceExtractionError(ValueError):
    """Raised when required invoice fields cannot be extracted reliably."""


@dataclass(frozen=True)
class PositionedLine:
    text: str
    confidence: float
    x1: int
    y1: int
    x2: int
    y2: int

    @property
    def center_x(self) -> float:
        return (self.x1 + self.x2) / 2

    @property
    def center_y(self) -> float:
        return (self.y1 + self.y2) / 2

    @property
    def width(self) -> int:
        return self.x2 - self.x1


@dataclass(frozen=True)
class ExtractedInvoice:
    """Fields expected by the matching and risk-detection pipeline."""

    invoice_id: str
    invoice_number: str
    invoice_date: str
    seller_name: str
    buyer_name: str
    product_category: str
    product_name: str
    quantity: float
    amount: float
    tax_amount: float
    total_amount: float

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def _read_ocr_json(path: Path) -> dict[str, Any]:
    if not path.is_file():
        raise FileNotFoundError(f"找不到OCR结果文件：{path}")
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise InvoiceExtractionError(f"OCR结果不是有效的UTF-8 JSON：{path}") from exc
    if not isinstance(payload, dict):
        raise InvoiceExtractionError("OCR JSON顶层必须是对象。")
    return payload


def _line_from_dict(raw: dict[str, Any]) -> PositionedLine | None:
    text = str(raw.get("text", "")).strip()
    box = raw.get("box")
    if not text or not isinstance(box, list) or not box:
        return None

    valid_points = [
        point
        for point in box
        if isinstance(point, list)
        and len(point) >= 2
        and isinstance(point[0], (int, float))
        and isinstance(point[1], (int, float))
    ]
    if not valid_points:
        return None

    xs = [int(round(point[0])) for point in valid_points]
    ys = [int(round(point[1])) for point in valid_points]
    return PositionedLine(
        text=text,
        confidence=float(raw.get("confidence", 0.0)),
        x1=min(xs),
        y1=min(ys),
        x2=max(xs),
        y2=max(ys),
    )


def _load_lines(payload: dict[str, Any]) -> list[PositionedLine]:
    pages = payload.get("pages")
    if not isinstance(pages, list) or not pages:
        raise InvoiceExtractionError("OCR JSON中没有pages。")

    lines: list[PositionedLine] = []
    for page in pages:
        if not isinstance(page, dict):
            continue
        raw_lines = page.get("lines")
        if not isinstance(raw_lines, list):
            continue
        for raw_line in raw_lines:
            if isinstance(raw_line, dict):
                line = _line_from_dict(raw_line)
                if line is not None:
                    lines.append(line)

    if not lines:
        raise InvoiceExtractionError("OCR JSON中没有可用的文字和坐标。")
    return sorted(lines, key=lambda line: (line.center_y, line.center_x))


def _compact(text: str) -> str:
    return re.sub(r"\s+", "", text).replace("：", ":")


def _find_regex(
    lines: Iterable[PositionedLine],
    pattern: str,
    field_name: str,
) -> re.Match[str]:
    compiled = re.compile(pattern, flags=re.IGNORECASE)
    for line in lines:
        match = compiled.search(_compact(line.text))
        if match:
            return match
    raise InvoiceExtractionError(f"无法提取{field_name}。")


def _find_regex_optional(
    lines: Iterable[PositionedLine],
    pattern: str,
) -> re.Match[str] | None:
    """Return the first regex match, or None when an optional field is absent."""
    compiled = re.compile(pattern, flags=re.IGNORECASE)
    for line in lines:
        match = compiled.search(_compact(line.text))
        if match:
            return match
    return None


def _find_anchor(
    lines: Iterable[PositionedLine],
    patterns: Iterable[str],
    field_name: str,
) -> PositionedLine:
    compiled = [re.compile(pattern, flags=re.IGNORECASE) for pattern in patterns]
    for line in lines:
        compact = _compact(line.text)
        if any(pattern.search(compact) for pattern in compiled):
            return line
    raise InvoiceExtractionError(f"无法定位{field_name}锚点。")


def _parse_decimal(text: str, field_name: str) -> Decimal:
    normalized = (
        text.replace(",", "")
        .replace("￥", "")
        .replace("¥", "")
        .replace(" ", "")
        .strip()
    )
    match = re.search(r"-?\d+(?:\.\d+)?", normalized)
    if not match:
        raise InvoiceExtractionError(f"{field_name}不是有效数字：{text}")
    try:
        return Decimal(match.group())
    except InvalidOperation as exc:
        raise InvoiceExtractionError(f"{field_name}不是有效数字：{text}") from exc


def _parse_quantity(text: str) -> float:
    value = _parse_decimal(text, "数量")
    if value <= 0:
        raise InvoiceExtractionError("数量必须大于0。")
    return float(value)


def _normalized_numeric_text(text: str) -> str:
    """Keep only characters that can belong to one OCR numeric token."""
    return re.sub(r"[^0-9.\-]", "", text.replace(",", ""))


def _product_matches_amount(
    quantity: Decimal,
    unit_price: Decimal,
    amount: Decimal,
) -> bool:
    """Validate an OCR split with the invoice's two-decimal amount."""
    calculated = (quantity * unit_price).quantize(
        Decimal("0.01"),
        rounding=ROUND_HALF_UP,
    )
    expected = amount.quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
    return abs(calculated - expected) <= Decimal("0.01")


def _parse_quantity_from_table_line(
    line: PositionedLine,
    *,
    quantity_header: PositionedLine,
    unit_price_header: PositionedLine,
    amount: Decimal,
) -> float:
    """Parse quantity, including a quantity+unit-price OCR merged box."""
    column_boundary = (quantity_header.center_x + unit_price_header.center_x) / 2
    crosses_into_unit_price = line.x2 > column_boundary
    if not crosses_into_unit_price:
        return _parse_quantity(line.text)

    token = _normalized_numeric_text(line.text)
    split_candidates: list[tuple[tuple[int, int, Decimal], Decimal]] = []
    for split_at in range(1, len(token)):
        quantity_text = token[:split_at]
        unit_price_text = token[split_at:]
        if not re.fullmatch(r"\d+(?:\.\d+)?", quantity_text):
            continue
        if not re.fullmatch(r"\d+(?:\.\d+)?", unit_price_text):
            continue
        try:
            quantity = Decimal(quantity_text)
            unit_price = Decimal(unit_price_text)
        except InvalidOperation:
            continue
        if quantity <= 0 or unit_price <= 0:
            continue
        if not _product_matches_amount(quantity, unit_price, amount):
            continue
        score = (
            0 if quantity == quantity.to_integral_value() else 1,
            len(quantity_text),
            abs(quantity * unit_price - amount),
        )
        split_candidates.append((score, quantity))

    if split_candidates:
        split_candidates.sort(key=lambda candidate: candidate[0])
        return float(split_candidates[0][1])

    if line.x1 >= column_boundary and re.fullmatch(r"\d+(?:\.\d+)?", token):
        unit_price = Decimal(token)
        inferred = amount / unit_price if unit_price else Decimal("0")
        rounded_quantity = inferred.quantize(Decimal("1"), rounding=ROUND_HALF_UP)
        if rounded_quantity > 0 and _product_matches_amount(
            rounded_quantity,
            unit_price,
            amount,
        ):
            return float(rounded_quantity)

    raise InvoiceExtractionError(
        "数量与单价疑似被OCR合并，但无法依据金额关系可靠拆分："
        f"{line.text}"
    )


def _company_name_value(line: PositionedLine) -> str:
    return re.sub(r"^.*?名称\s*[:：]\s*", "", line.text).strip()


def _extract_company_names(
    lines: list[PositionedLine],
    *,
    table_header_y: float,
    total_y: float,
) -> tuple[str, str]:
    """Extract ``(buyer, seller)`` from either supported invoice layout."""
    names_above = [
        line
        for line in lines
        if line.center_y < table_header_y
        and re.search(r"名称\s*[:：]", line.text)
        and "项目名称" not in line.text
        and _company_name_value(line)
    ]

    if len(names_above) >= 2:
        # Common electronic invoice: buyer left, seller right.
        ordered = sorted(names_above, key=lambda line: line.center_x)
        return _company_name_value(ordered[0]), _company_name_value(ordered[-1])

    names_below = [
        line
        for line in lines
        if line.center_y > total_y
        and re.search(r"名称\s*[:：]", line.text)
        and "项目名称" not in line.text
        and _company_name_value(line)
    ]
    if names_above and names_below:
        # Synthetic template: buyer above the table, seller below the totals.
        return _company_name_value(names_above[0]), _company_name_value(names_below[0])

    raise InvoiceExtractionError("无法根据发票分区同时提取购买方和销售方名称。")


def _find_table_header(
    lines: list[PositionedLine],
    patterns: Iterable[str],
    field_name: str,
) -> PositionedLine:
    candidates: list[PositionedLine] = []
    compiled = [re.compile(pattern, flags=re.IGNORECASE) for pattern in patterns]
    for line in lines:
        compact = _compact(line.text)
        if any(pattern.fullmatch(compact) for pattern in compiled):
            candidates.append(line)
    if not candidates and field_name == "数量":
        # PaddleOCR may split the narrow “数量” header into two boxes.
        number_parts = [line for line in lines if _compact(line.text) == "数"]
        quantity_parts = [line for line in lines if _compact(line.text) == "量"]
        pairs = [
            (left, right)
            for left in number_parts
            for right in quantity_parts
            if abs(left.center_y - right.center_y) <= 25
            and 0 <= right.center_x - left.center_x <= 120
        ]
        if pairs:
            left, right = min(pairs, key=lambda pair: pair[0].center_y)
            candidates.append(
                PositionedLine(
                    text="数量",
                    confidence=min(left.confidence, right.confidence),
                    x1=min(left.x1, right.x1),
                    y1=min(left.y1, right.y1),
                    x2=max(left.x2, right.x2),
                    y2=max(left.y2, right.y2),
                )
            )
    if not candidates:
        raise InvoiceExtractionError(f"无法定位表头：{field_name}。")
    return min(candidates, key=lambda line: line.center_y)


def _find_item_value(
    lines: list[PositionedLine],
    *,
    header: PositionedLine,
    item_bottom_y: float,
    field_name: str,
) -> PositionedLine:
    """Find the value below a header and inside the same visual column."""
    # Values may be left- or right-aligned inside a wide cell, so their text
    # center is not necessarily under the short centered header text.
    x_margin = max(120, header.width * 2.0)
    candidates = [
        line
        for line in lines
        if line.center_y > header.y2
        and line.center_y < item_bottom_y
        and header.x1 - x_margin <= line.center_x <= header.x2 + x_margin
    ]
    if not candidates:
        raise InvoiceExtractionError(f"无法根据表头提取{field_name}。")
    return min(
        candidates,
        key=lambda line: (
            abs(line.center_x - header.center_x),
            -line.confidence,
        ),
    )


def _parse_project_name(text: str) -> tuple[str, str]:
    """Parse the mock tax-classification form: *category*product name."""
    compact = text.strip()
    match = re.match(r"^[*＊]([^*＊]+)[*＊](.+)$", compact)
    if not match:
        raise InvoiceExtractionError(
            "项目名称未采用“*商品类别*商品名称”的测试格式："
            f"{text}"
        )
    category = match.group(1).strip()
    product_name = match.group(2).strip()
    if not category or not product_name:
        raise InvoiceExtractionError(f"项目名称解析结果为空：{text}")
    return category, product_name


def _collect_project_text(
    lines: list[PositionedLine],
    *,
    first_line: PositionedLine,
    project_header: PositionedLine,
    next_header: PositionedLine,
    item_bottom_y: float,
) -> str:
    """Join a project name that PaddleOCR split across multiple lines."""
    right_boundary = (project_header.center_x + next_header.center_x) / 2
    excluded = {
        "项目名称",
        "规格型号",
        "单位",
        "数",
        "量",
        "数量",
        "单价",
        "金额",
        "税率/征收率",
        "税额",
        "合计",
    }
    continuations = [
        line
        for line in lines
        if line is not first_line
        and line.center_y > first_line.center_y
        and line.center_y < item_bottom_y
        and line.center_x < right_boundary
        and _compact(line.text) not in excluded
        and not re.fullmatch(r"[￥¥]?\d+(?:\.\d+)?%?", _compact(line.text))
    ]
    ordered = [
        first_line,
        *sorted(continuations, key=lambda line: (line.center_y, line.center_x)),
    ]
    return "".join(line.text.strip() for line in ordered)


def _extract_total_amount(lines: list[PositionedLine]) -> tuple[Decimal, float]:
    candidates = [
        line
        for line in lines
        if re.search(r"[（(]小写[)）]", line.text) and re.search(r"\d", line.text)
    ]
    if not candidates:
        raise InvoiceExtractionError("无法定位价税合计（小写）。")
    line = candidates[0]
    text = re.sub(r"^.*?[（(]小写[)）]\s*", "", line.text)
    return _parse_decimal(text, "价税合计"), line.center_y


def extract_invoice(ocr_json_path: str | Path) -> ExtractedInvoice:
    path = Path(ocr_json_path).expanduser().resolve()
    payload = _read_ocr_json(path)
    lines = _load_lines(payload)

    invoice_id_match = _find_regex_optional(
        lines,
        r"测试数据编号[:：]?(INV\d+)",
    )
    invoice_number_match = _find_regex(
        lines,
        r"\b(\d{20})\b",
        "20位发票号码",
    )
    date_match = _find_regex(
        lines,
        r"(\d{4})年0?(\d{1,2})月0?(\d{1,2})日",
        "开票日期",
    )
    invoice_date = date(
        int(date_match.group(1)),
        int(date_match.group(2)),
        int(date_match.group(3)),
    ).isoformat()

    project_header = _find_table_header(
        lines,
        [r"项目名称"],
        "项目名称",
    )
    specification_header = _find_table_header(
        lines,
        [r"规格型号"],
        "规格型号",
    )
    quantity_header = _find_table_header(lines, [r"数量"], "数量")
    unit_price_header = _find_table_header(lines, [r"单价"], "单价")
    amount_header = _find_table_header(lines, [r"金额"], "金额")
    tax_header = _find_table_header(lines, [r"税额"], "税额")
    summary_anchor = _find_anchor(lines, [r"^合计$"], "合计")

    project_line = _find_item_value(
        lines,
        header=project_header,
        item_bottom_y=summary_anchor.center_y,
        field_name="项目名称",
    )
    quantity_line = _find_item_value(
        lines,
        header=quantity_header,
        item_bottom_y=summary_anchor.center_y,
        field_name="数量",
    )
    amount_line = _find_item_value(
        lines,
        header=amount_header,
        item_bottom_y=summary_anchor.center_y,
        field_name="金额",
    )
    tax_line = _find_item_value(
        lines,
        header=tax_header,
        item_bottom_y=summary_anchor.center_y,
        field_name="税额",
    )

    project_text = _collect_project_text(
        lines,
        first_line=project_line,
        project_header=project_header,
        next_header=specification_header,
        item_bottom_y=summary_anchor.center_y,
    )
    product_category, product_name = _parse_project_name(project_text)
    amount = _parse_decimal(amount_line.text, "金额")
    tax_amount = _parse_decimal(tax_line.text, "税额")
    total_amount, total_y = _extract_total_amount(lines)

    if abs(amount + tax_amount - total_amount) > Decimal("0.01"):
        raise InvoiceExtractionError(
            "金额校验失败：amount + tax_amount != total_amount；"
            f"{amount} + {tax_amount} != {total_amount}"
        )

    buyer_name, seller_name = _extract_company_names(
        lines,
        table_header_y=project_header.center_y,
        total_y=total_y,
    )
    invoice_number = invoice_number_match.group(1)
    invoice_id = (
        invoice_id_match.group(1).upper()
        if invoice_id_match is not None
        else f"DOC-{invoice_number[-8:]}"
    )

    return ExtractedInvoice(
        invoice_id=invoice_id,
        invoice_number=invoice_number,
        invoice_date=invoice_date,
        seller_name=seller_name,
        buyer_name=buyer_name,
        product_category=product_category,
        product_name=product_name,
        quantity=_parse_quantity_from_table_line(
            quantity_line,
            quantity_header=quantity_header,
            unit_price_header=unit_price_header,
            amount=amount,
        ),
        amount=float(amount),
        tax_amount=float(tax_amount),
        total_amount=float(total_amount),
    )


def save_extraction(
    invoice: ExtractedInvoice,
    output_path: str | Path,
) -> Path:
    path = Path(output_path).expanduser().resolve()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(invoice.to_dict(), ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return path


def compare_with_workbook(
    invoice: ExtractedInvoice,
    workbook_path: str | Path = DEFAULT_INVOICE_WORKBOOK,
) -> dict[str, dict[str, Any]]:
    """Compare business fields with the source row used as OCR ground truth."""
    path = Path(workbook_path).expanduser().resolve()
    dataframe = pd.read_excel(path, sheet_name="invoice_data")
    expected_rows = dataframe.loc[
        dataframe["invoice_id"].astype(str).str.strip() == invoice.invoice_id
    ]
    if len(expected_rows) != 1:
        raise InvoiceExtractionError(
            f"标准数据中应恰好存在一条{invoice.invoice_id}，实际为{len(expected_rows)}条。"
        )

    expected = expected_rows.iloc[0]
    actual = invoice.to_dict()
    comparisons: dict[str, dict[str, Any]] = {}

    for field in [
        "invoice_id",
        "seller_name",
        "buyer_name",
        "product_category",
        "product_name",
    ]:
        expected_value = str(expected[field]).strip()
        actual_value = str(actual[field]).strip()
        comparisons[field] = {
            "expected": expected_value,
            "actual": actual_value,
            "match": expected_value == actual_value,
        }

    expected_date = pd.to_datetime(expected["invoice_date"]).strftime("%Y-%m-%d")
    comparisons["invoice_date"] = {
        "expected": expected_date,
        "actual": invoice.invoice_date,
        "match": expected_date == invoice.invoice_date,
    }

    for field in ["quantity", "amount", "tax_amount", "total_amount"]:
        expected_value = float(expected[field])
        actual_value = float(actual[field])
        comparisons[field] = {
            "expected": expected_value,
            "actual": actual_value,
            "match": abs(expected_value - actual_value) <= 0.01,
        }

    return comparisons


def _print_comparison(comparisons: dict[str, dict[str, Any]]) -> bool:
    print("\n与 invoices.xlsx 标准答案对比：")
    all_match = True
    for field, result in comparisons.items():
        matched = bool(result["match"])
        all_match = all_match and matched
        status = "PASS" if matched else "FAIL"
        print(
            f"  {status:4s} {field}: "
            f"识别={result['actual']!r}，标准={result['expected']!r}"
        )
    return all_match


def run_cli() -> None:
    parser = argparse.ArgumentParser(description="从OCR JSON提取结构化发票字段。")
    parser.add_argument("ocr_json", help="ocr_service.py生成的单个OCR JSON文件。")
    parser.add_argument(
        "--output-dir",
        default=str(DEFAULT_OUTPUT_DIR),
        help=f"结构化JSON输出目录，默认：{DEFAULT_OUTPUT_DIR}",
    )
    parser.add_argument(
        "--verify",
        action="store_true",
        help="与invoices.xlsx中的标准记录逐字段比较。",
    )
    args = parser.parse_args()

    input_path = Path(args.ocr_json).expanduser().resolve()
    invoice = extract_invoice(input_path)
    output_path = (
        Path(args.output_dir).expanduser().resolve()
        / f"{invoice.invoice_id}_extracted.json"
    )
    saved_path = save_extraction(invoice, output_path)

    print("结构化发票：")
    print(json.dumps(invoice.to_dict(), ensure_ascii=False, indent=2))
    print(f"\n已保存：{saved_path}")

    if args.verify:
        comparisons = compare_with_workbook(invoice)
        if not _print_comparison(comparisons):
            raise SystemExit("存在字段提取错误。")


if __name__ == "__main__":
    run_cli()
